let options = [
    'All',
    'Echo & Alexa',
    'Amazon Devices',
    'Amazon Fashion',
    'Amazon Fresh',
    'Amazon Pharmacy',
    'Appliances',
    'Apps & Games',
    'Baby',
    'Beauty',
    'Books',
    'Car & Motorbike',
    'Clothing & Accessories',
    'Computers & Accessories',
    'Electronics',
    'Entertainment',
    'Gift Cards',
    'Grocery',
    'Health & Personal Care',
    'Home & Kitchen',
    'Industrial & Scientific',
    'Jewellery',
    'Kindle Store',
    'Luggage',
    'Mobiles & Accessories',
    'Movies & TV Shows',
    'Music',
    'Musical Instruments',
    'Office Products',
    'Pet Supplies',
    'Prime Video',
    'Shoes & Handbags',
    'Software',
    'Sports, Fitness & Outdoors',
    'Stationery & Office Supplies',
    'Toys & Games',
    'Video Games',
    'Watches'
];

export {
    options
}